services:
  app:
    image: ghcr.io/benjamingolder/cookidoo-planner:latest
    container_name: cookidoo-planner
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=8080
      - LOG_FILE=/tmp/debug.log
    volumes:
      - app-data:/app/data
    ports:
      - "9080:8080"

volumes:
  app-data:
