services:
  app:
    image: ghcr.io/benjamingolder/cookidoo-planner:latest
    container_name: cookidoo-planner
    restart: unless-stopped
    environment:
      - PORT=8080
      - LOG_FILE=/tmp/debug.log
      - DATA_DIR=/app/data
      - ADMIN_PASSWORD=changeme
      - SECRET_KEY=changeme-to-random-string
    volumes:
      - /share/Container/meal-plan:/app/data
    ports:
      - "9080:8080"
